# -*- coding: utf-8 -*-
"""Countdown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZTUHD-2ryJEdWSBpkpgFfToxvJcXNdB
"""

import time
a = int(input("Enter from which number you want to start from"))
while a > 0:
  print(a)
  time.sleep(1)
  a -= 1

print("Time Up")