# -*- coding: utf-8 -*-
"""Decision tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rviLWDMujWxK9TChQo56xYfWP7iI17Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/Social_Network_Ads (1).csv')
X = dataset.iloc[:, 2:4].values
y = dataset.iloc[:, -1].values

dataset.isnull()

dataset.isna().sum()

print(dataset.head(10))

print(dataset.tail(10))

print(dataset.describe())

print(dataset.info())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot = True)

from sklearn.metrics import accuracy_score
ass = accuracy_score(y_test, y_pred)
print(ass)

from sklearn.tree import plot_tree
plt.figure(figsize = (100, 100))
plot_tree(classifier, filled = True)
plt.show()