# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185GrBeMd0gAHAdsSP6Lg7KMd5eGyUr85
"""

!pip install wordfreq
import random
from wordfreq import top_n_list

hangman_stages = [
    """
      -------
      |     |
      |
      |
      |
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |
      |
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |     |
      |
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |    /|
      |
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |    /|\\
      |
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |    /|\\
      |    /
      |
    ---------
    """,
    """
      -------
      |     |
      |     O
      |    /|\\
      |    / \\
      |
    ---------
    """
]

word_list = top_n_list('en', 10000)
filtered_words = []
for w in word_list:
  if w.isalpha() and 5 <= len(w) <= 10:
    filtered_words.append(w.lower())

e_word_list = []
m_word_list = []
h_word_list = []

for i in filtered_words:
  if len(i) <= 6:
    e_word_list.append(i)
  elif len(i) <= 8:
    m_word_list.append(i)
  else:
    h_word_list.append(i)

print("Welcome to Hangman")
print("""

Choose Your Difficulty
1) Easy - Type E (short words)
2) Medium - Type M (medium words)
3)Hard - Type H (long words)

""")

word = ""
while True:
  difficulty = input("Enter Difficulty: ").upper()
  if difficulty == "E":

    if e_word_list:
        word = random.choice(e_word_list)
        break
    #else:
        #print("No easy words available. Please choose another difficulty.")
  elif difficulty == "M":
    if m_word_list:
        word = random.choice(m_word_list)
        break
    #else:
        #print("No medium words available. Please choose another difficulty.")
  elif difficulty == "H":
    if h_word_list:
        word = random.choice(h_word_list)
        break
    #else:
        #print("No hard words available. Please choose another difficulty.")
  else:
    print("Invalid Input. Please enter E, M, or H.")

lives = 6
total_guesses = 0
guessed_letters = []
wrong_letters = []
display_word = ["_"] * len(word)
initial_reveal_indices = []
if len(word) >= 2:
    initial_reveal_indices = random.sample(range(len(word)), 2)

for i in range(len(word)):
    if i in initial_reveal_indices:
        display_word[i] = word[i]
        if word[i] not in guessed_letters: # Add revealed letters to guessed_letters
            guessed_letters.append(word[i])

print("The secret word has " + str(len(word)) + " letters")
print("Word:", " ".join(display_word)) # Display the initially revealed word


while lives > 0 and "_" in display_word:
  print(hangman_stages[6 - lives]) # Display the hangman stage
  print("Wrong letters:", ", ".join(wrong_letters))
  print("Word:", " ".join(display_word))

  guess = input("Guess a letter: ").lower()

  if len(guess) != 1 or not guess.isalpha():
    print("Invalid input. Please guess a single letter.")
    continue

  if guess in guessed_letters or guess in wrong_letters:
    print("You already guessed that letter.")
    continue

  if guess in word:
    print("Good guess!")
    for i in range(len(word)):
      if word[i] == guess:
        display_word[i] = guess
    guessed_letters.append(guess)
  else:
    print("Wrong guess!")
    lives -= 1
    wrong_letters.append(guess)

if "_" not in display_word:
  print("\nCongratulations! You guessed the word:", word)
else:
  print(hangman_stages[6 - lives]) # Display final hangman state
  print("\nGame over! You ran out of lives. The word was:", word)
