# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y94TpIk89yzuO1jaawpmav0AgxDJWiXa
"""

print("Welcome to Health Chatbot")
response = {
    "Headache" : "Drink Some Water , If symptoms persist , apply some balm on your head or visit your doctor",
    "Burn" : "Rinse in water and apply some cream , if its a major burn , then visit your doctor",
    "Cough" : "Drink hot water and take some cough syrup , if symptoms persist , visit your doctor",
    "Fever" : "Take a fever tablet , if symptoms persist , visit your doctor",
    "Stomach Ache" : "Try a warm compress and avoid heavy meals, if it persists, see a doctor",
    "Sore Throat" : "Gargle with salt water and drink warm tea, if symptoms worsen, consult a doctor",
    "Rash" : "Avoid scratching, keep the area clean and dry. Apply a mild anti-itch cream. If it spreads or is painful, see a doctor",
    "Insomnia" : "Try to establish a regular sleep schedule, avoid caffeine before bed, and ensure your sleep environment is comfortable. If you still have trouble, consider talking to a doctor.",
    "Nausea" : "Sip on clear fluids, eat bland foods like crackers, and avoid strong smells. If it persists, consult a doctor.",
    "Back Pain" : "Apply a heat pack or ice pack, gentle stretching, and over-the-counter pain relievers. If severe or chronic, see a doctor.",
    "Allergies" : "Identify and avoid triggers, take antihistamines, and keep windows closed during high pollen counts. If severe, consult an allergist.",
    "Indigestion" : "Eat smaller meals, avoid spicy or fatty foods, and consider antacids. If it's frequent or severe, see a doctor.",
    "Flu" : "Rest, drink plenty of fluids, and consider over-the-counter flu remedies. If symptoms worsen or become severe, consult a doctor.",
    "Cold" : "Get plenty of rest, drink fluids, and use decongestants or pain relievers for symptoms. It usually resolves on its own.",
    "Diarrhea" : "Drink plenty of clear fluids to prevent dehydration, eat bland foods, and avoid dairy and fatty foods. If severe or prolonged, seek medical attention.",
    "Constipation" : "Increase fiber intake, drink more water, and try light exercise. If it persists, a mild laxative or doctor's visit might be needed.",
    "Conjunctivitis" : "Avoid touching your eyes, use warm compresses, and if it's bacterial, antibiotic eye drops from a doctor might be necessary."
}
while True:
  user = input("User :").lower()
  if user == "bye" or user == "goodbye":
    print("Take Care , Bye")
    break
  found = False
  for key in response:
    if key.lower() in user:
      print(response[key])
      found = True
      break
  if not found:
    print("I don't understand")