# -*- coding: utf-8 -*-
"""MovieRecommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlKPcgH2kva3g5s67jKOMCmh9sqyqmbH
"""

movies = [
    {"name": "Avengers", "genre": "Action"},
    {"name": "Titanic", "genre": "Drama"},
    {"name": "Inception", "genre": "Sci-Fi"},
    {"name": "Interstellar", "genre": "Sci-Fi"},
    {"name": "Notebook", "genre": "Drama"}
]

def recommend(m_name):
  if m_name not in movies:
    return "Movie not found"
  b = movies[m_name]
  rec = []
  for movie_title , c in movies.items():
    if movie_title != m_name:
      if any(x in c for x in b):
        rec.append(movie_title)
  return rec

def recommendg(m_genre):
  if m_genre not in movies.items():
    return "Genre not found"
  b = movies[m_genre]
  rec = []
  for movie_title, c in movies.items():
    if m_genre in c:
      rec.append(movie_title)
  return rec

genre = input("Enter a genre you like: ").capitalize()

print("\nRecommended movies:")
found = False

for movie in movies:
    if movie["genre"] == genre:
        print("-", movie["name"])
        found = True

if not found:
    print("No movies found for this genre.")