# -*- coding: utf-8 -*-
"""PASSWORD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1o7UA3vcfg2zIKmgAgszMIF7EWI2nyT
"""

import random

print("Welcome to the password generator!")
print("How many letters would you like in your password?")
int_letters = int(input())
print("How many symbols would you like in your password?")
int_symbols = int(input())
print("How many numbers would you like in your password?")
int_numbers = int(input())
password = []
for i in range(int_letters):
    password.append(chr(random.randint(65, 90)))
for i in range(int_symbols):
    password.append(chr(random.randint(33, 47)))
for i in range(int_numbers):
    password.append(chr(random.randint(48, 57)))
random.shuffle(password)
password = "".join(password)
print("Therefore your password is " + password)